<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.7.3 on linux)" generated="20230321 07:33:11.960" rpa="false" schemaversion="3">
<suite id="s1" name="Kiosk-Loop" source="/home/pi/robot/kiosk-loop.robot">
<kw name="Open Browser" library="SeleniumLibrary" type="SETUP">
<arg>https://champ.tta.or.kr/usr/EgovUsrSelectBoardList.do?bbsId=BBSMSTR_AAAAAAAAAAAA&amp;baseUsrMenuNo=5&amp;imgNum=1</arg>
<arg>chrome</arg>
<arg>options=add_argument('--start-maximized');add_argument('--no-sandbox');add_argument('--kiosk');add_argument('--disable-infobars')</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20230321 07:33:13.060" level="INFO">Opening browser 'chrome' to base url 'https://champ.tta.or.kr/usr/EgovUsrSelectBoardList.do?bbsId=BBSMSTR_AAAAAAAAAAAA&amp;baseUsrMenuNo=5&amp;imgNum=1'.</msg>
<msg timestamp="20230321 07:33:19.583" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x75859510&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/394e9a02c89f7f878007b2629c04c23e/screenshot</msg>
<msg timestamp="20230321 07:33:19.600" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x758595d0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/394e9a02c89f7f878007b2629c04c23e/screenshot</msg>
<msg timestamp="20230321 07:33:19.626" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x758596b0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/394e9a02c89f7f878007b2629c04c23e/screenshot</msg>
<msg timestamp="20230321 07:33:19.635" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=40337): Max retries exceeded with url: /session/394e9a02c89f7f878007b2629c04c23e/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x758b1f70&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<status status="FAIL" starttime="20230321 07:33:13.055" endtime="20230321 07:33:19.637"/>
</kw>
<test id="s1-t1" name="Find Beacon Notice" line="7">
<tag>robot:exit</tag>
<status status="FAIL" starttime="20230321 07:33:19.644" endtime="20230321 07:33:19.659">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t2" name="Run Kiosk Mode" line="10">
<tag>robot:exit</tag>
<status status="FAIL" starttime="20230321 07:33:19.666" endtime="20230321 07:33:19.677">Test execution stopped due to a fatal error.</status>
</test>
<status status="FAIL" starttime="20230321 07:33:11.966" endtime="20230321 07:33:19.691">Suite setup failed:
Execution terminated by signal</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="0" skip="0" info="combined" combined="NOT robot:exit">NOT robot:exit</stat>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="Kiosk-Loop">Kiosk-Loop</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230321 07:33:19.583" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x75859510&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/394e9a02c89f7f878007b2629c04c23e/screenshot</msg>
<msg timestamp="20230321 07:33:19.600" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x758595d0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/394e9a02c89f7f878007b2629c04c23e/screenshot</msg>
<msg timestamp="20230321 07:33:19.626" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x758596b0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/394e9a02c89f7f878007b2629c04c23e/screenshot</msg>
<msg timestamp="20230321 07:33:19.635" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=40337): Max retries exceeded with url: /session/394e9a02c89f7f878007b2629c04c23e/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x758b1f70&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
</errors>
</robot>
